//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUserTokens", ReplyAction="*")]
        void updateUserTokens(int id, int tokens);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUserTokens", ReplyAction="*")]
        System.Threading.Tasks.Task updateUserTokensAsync(int id, int tokens);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateChallengeReward", ReplyAction="*")]
        void updateChallengeReward(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateChallengeReward", ReplyAction="*")]
        System.Threading.Tasks.Task updateChallengeRewardAsync(int id);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        Frontend.ServiceReference1.addUserResponse addUser(Frontend.ServiceReference1.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.addUserResponse> addUserAsync(Frontend.ServiceReference1.addUserRequest request);
        
        // CODEGEN: Generating message contract since element name description from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addChallenge", ReplyAction="*")]
        Frontend.ServiceReference1.addChallengeResponse addChallenge(Frontend.ServiceReference1.addChallengeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addChallenge", ReplyAction="*")]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.addChallengeResponse> addChallengeAsync(Frontend.ServiceReference1.addChallengeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteChallenge", ReplyAction="*")]
        void deleteChallenge(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteChallenge", ReplyAction="*")]
        System.Threading.Tasks.Task deleteChallengeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addParticipant", ReplyAction="*")]
        void addParticipant(int challengeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addParticipant", ReplyAction="*")]
        System.Threading.Tasks.Task addParticipantAsync(int challengeId, int userId);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserbyCredentials", ReplyAction="*")]
        Frontend.ServiceReference1.getUserbyCredentialsResponse getUserbyCredentials(Frontend.ServiceReference1.getUserbyCredentialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserbyCredentials", ReplyAction="*")]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getUserbyCredentialsResponse> getUserbyCredentialsAsync(Frontend.ServiceReference1.getUserbyCredentialsRequest request);
        
        // CODEGEN: Generating message contract since element name getUserbyIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserbyId", ReplyAction="*")]
        Frontend.ServiceReference1.getUserbyIdResponse getUserbyId(Frontend.ServiceReference1.getUserbyIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserbyId", ReplyAction="*")]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getUserbyIdResponse> getUserbyIdAsync(Frontend.ServiceReference1.getUserbyIdRequest request);
        
        // CODEGEN: Generating message contract since element name getHostedChallengesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHostedChallenges", ReplyAction="*")]
        Frontend.ServiceReference1.getHostedChallengesResponse getHostedChallenges(Frontend.ServiceReference1.getHostedChallengesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHostedChallenges", ReplyAction="*")]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getHostedChallengesResponse> getHostedChallengesAsync(Frontend.ServiceReference1.getHostedChallengesRequest request);
        
        // CODEGEN: Generating message contract since element name getActiveChallengesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getActiveChallenges", ReplyAction="*")]
        Frontend.ServiceReference1.getActiveChallengesResponse getActiveChallenges(Frontend.ServiceReference1.getActiveChallengesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getActiveChallenges", ReplyAction="*")]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getActiveChallengesResponse> getActiveChallengesAsync(Frontend.ServiceReference1.getActiveChallengesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaxChallengeId", ReplyAction="*")]
        int getMaxChallengeId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaxChallengeId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getMaxChallengeIdAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(Frontend.ServiceReference1.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int tokens;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(int id, string username, string password, int tokens) {
            this.id = id;
            this.username = username;
            this.password = password;
            this.tokens = tokens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(Frontend.ServiceReference1.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addUserResponseBody {
        
        public addUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addChallengeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addChallenge", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.addChallengeRequestBody Body;
        
        public addChallengeRequest() {
        }
        
        public addChallengeRequest(Frontend.ServiceReference1.addChallengeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addChallengeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int creator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int reward;
        
        public addChallengeRequestBody() {
        }
        
        public addChallengeRequestBody(int id, int creator, string description, int reward) {
            this.id = id;
            this.creator = creator;
            this.description = description;
            this.reward = reward;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addChallengeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addChallengeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.addChallengeResponseBody Body;
        
        public addChallengeResponse() {
        }
        
        public addChallengeResponse(Frontend.ServiceReference1.addChallengeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addChallengeResponseBody {
        
        public addChallengeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserbyCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserbyCredentials", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getUserbyCredentialsRequestBody Body;
        
        public getUserbyCredentialsRequest() {
        }
        
        public getUserbyCredentialsRequest(Frontend.ServiceReference1.getUserbyCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserbyCredentialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getUserbyCredentialsRequestBody() {
        }
        
        public getUserbyCredentialsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserbyCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserbyCredentialsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getUserbyCredentialsResponseBody Body;
        
        public getUserbyCredentialsResponse() {
        }
        
        public getUserbyCredentialsResponse(Frontend.ServiceReference1.getUserbyCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserbyCredentialsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserbyCredentialsResult;
        
        public getUserbyCredentialsResponseBody() {
        }
        
        public getUserbyCredentialsResponseBody(string getUserbyCredentialsResult) {
            this.getUserbyCredentialsResult = getUserbyCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserbyIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserbyId", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getUserbyIdRequestBody Body;
        
        public getUserbyIdRequest() {
        }
        
        public getUserbyIdRequest(Frontend.ServiceReference1.getUserbyIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserbyIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getUserbyIdRequestBody() {
        }
        
        public getUserbyIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserbyIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserbyIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getUserbyIdResponseBody Body;
        
        public getUserbyIdResponse() {
        }
        
        public getUserbyIdResponse(Frontend.ServiceReference1.getUserbyIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserbyIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserbyIdResult;
        
        public getUserbyIdResponseBody() {
        }
        
        public getUserbyIdResponseBody(string getUserbyIdResult) {
            this.getUserbyIdResult = getUserbyIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHostedChallengesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHostedChallenges", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getHostedChallengesRequestBody Body;
        
        public getHostedChallengesRequest() {
        }
        
        public getHostedChallengesRequest(Frontend.ServiceReference1.getHostedChallengesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHostedChallengesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public getHostedChallengesRequestBody() {
        }
        
        public getHostedChallengesRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHostedChallengesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHostedChallengesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getHostedChallengesResponseBody Body;
        
        public getHostedChallengesResponse() {
        }
        
        public getHostedChallengesResponse(Frontend.ServiceReference1.getHostedChallengesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHostedChallengesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHostedChallengesResult;
        
        public getHostedChallengesResponseBody() {
        }
        
        public getHostedChallengesResponseBody(string getHostedChallengesResult) {
            this.getHostedChallengesResult = getHostedChallengesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getActiveChallengesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getActiveChallenges", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getActiveChallengesRequestBody Body;
        
        public getActiveChallengesRequest() {
        }
        
        public getActiveChallengesRequest(Frontend.ServiceReference1.getActiveChallengesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getActiveChallengesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public getActiveChallengesRequestBody() {
        }
        
        public getActiveChallengesRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getActiveChallengesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getActiveChallengesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Frontend.ServiceReference1.getActiveChallengesResponseBody Body;
        
        public getActiveChallengesResponse() {
        }
        
        public getActiveChallengesResponse(Frontend.ServiceReference1.getActiveChallengesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getActiveChallengesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getActiveChallengesResult;
        
        public getActiveChallengesResponseBody() {
        }
        
        public getActiveChallengesResponseBody(string getActiveChallengesResult) {
            this.getActiveChallengesResult = getActiveChallengesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Frontend.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Frontend.ServiceReference1.WebService1Soap>, Frontend.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void updateUserTokens(int id, int tokens) {
            base.Channel.updateUserTokens(id, tokens);
        }
        
        public System.Threading.Tasks.Task updateUserTokensAsync(int id, int tokens) {
            return base.Channel.updateUserTokensAsync(id, tokens);
        }
        
        public void updateChallengeReward(int id) {
            base.Channel.updateChallengeReward(id);
        }
        
        public System.Threading.Tasks.Task updateChallengeRewardAsync(int id) {
            return base.Channel.updateChallengeRewardAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Frontend.ServiceReference1.addUserResponse Frontend.ServiceReference1.WebService1Soap.addUser(Frontend.ServiceReference1.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public void addUser(int id, string username, string password, int tokens) {
            Frontend.ServiceReference1.addUserRequest inValue = new Frontend.ServiceReference1.addUserRequest();
            inValue.Body = new Frontend.ServiceReference1.addUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.tokens = tokens;
            Frontend.ServiceReference1.addUserResponse retVal = ((Frontend.ServiceReference1.WebService1Soap)(this)).addUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.addUserResponse> Frontend.ServiceReference1.WebService1Soap.addUserAsync(Frontend.ServiceReference1.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Frontend.ServiceReference1.addUserResponse> addUserAsync(int id, string username, string password, int tokens) {
            Frontend.ServiceReference1.addUserRequest inValue = new Frontend.ServiceReference1.addUserRequest();
            inValue.Body = new Frontend.ServiceReference1.addUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.tokens = tokens;
            return ((Frontend.ServiceReference1.WebService1Soap)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Frontend.ServiceReference1.addChallengeResponse Frontend.ServiceReference1.WebService1Soap.addChallenge(Frontend.ServiceReference1.addChallengeRequest request) {
            return base.Channel.addChallenge(request);
        }
        
        public void addChallenge(int id, int creator, string description, int reward) {
            Frontend.ServiceReference1.addChallengeRequest inValue = new Frontend.ServiceReference1.addChallengeRequest();
            inValue.Body = new Frontend.ServiceReference1.addChallengeRequestBody();
            inValue.Body.id = id;
            inValue.Body.creator = creator;
            inValue.Body.description = description;
            inValue.Body.reward = reward;
            Frontend.ServiceReference1.addChallengeResponse retVal = ((Frontend.ServiceReference1.WebService1Soap)(this)).addChallenge(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.addChallengeResponse> Frontend.ServiceReference1.WebService1Soap.addChallengeAsync(Frontend.ServiceReference1.addChallengeRequest request) {
            return base.Channel.addChallengeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Frontend.ServiceReference1.addChallengeResponse> addChallengeAsync(int id, int creator, string description, int reward) {
            Frontend.ServiceReference1.addChallengeRequest inValue = new Frontend.ServiceReference1.addChallengeRequest();
            inValue.Body = new Frontend.ServiceReference1.addChallengeRequestBody();
            inValue.Body.id = id;
            inValue.Body.creator = creator;
            inValue.Body.description = description;
            inValue.Body.reward = reward;
            return ((Frontend.ServiceReference1.WebService1Soap)(this)).addChallengeAsync(inValue);
        }
        
        public void deleteChallenge(int id) {
            base.Channel.deleteChallenge(id);
        }
        
        public System.Threading.Tasks.Task deleteChallengeAsync(int id) {
            return base.Channel.deleteChallengeAsync(id);
        }
        
        public void addParticipant(int challengeId, int userId) {
            base.Channel.addParticipant(challengeId, userId);
        }
        
        public System.Threading.Tasks.Task addParticipantAsync(int challengeId, int userId) {
            return base.Channel.addParticipantAsync(challengeId, userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Frontend.ServiceReference1.getUserbyCredentialsResponse Frontend.ServiceReference1.WebService1Soap.getUserbyCredentials(Frontend.ServiceReference1.getUserbyCredentialsRequest request) {
            return base.Channel.getUserbyCredentials(request);
        }
        
        public string getUserbyCredentials(string username, string password) {
            Frontend.ServiceReference1.getUserbyCredentialsRequest inValue = new Frontend.ServiceReference1.getUserbyCredentialsRequest();
            inValue.Body = new Frontend.ServiceReference1.getUserbyCredentialsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Frontend.ServiceReference1.getUserbyCredentialsResponse retVal = ((Frontend.ServiceReference1.WebService1Soap)(this)).getUserbyCredentials(inValue);
            return retVal.Body.getUserbyCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getUserbyCredentialsResponse> Frontend.ServiceReference1.WebService1Soap.getUserbyCredentialsAsync(Frontend.ServiceReference1.getUserbyCredentialsRequest request) {
            return base.Channel.getUserbyCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Frontend.ServiceReference1.getUserbyCredentialsResponse> getUserbyCredentialsAsync(string username, string password) {
            Frontend.ServiceReference1.getUserbyCredentialsRequest inValue = new Frontend.ServiceReference1.getUserbyCredentialsRequest();
            inValue.Body = new Frontend.ServiceReference1.getUserbyCredentialsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Frontend.ServiceReference1.WebService1Soap)(this)).getUserbyCredentialsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Frontend.ServiceReference1.getUserbyIdResponse Frontend.ServiceReference1.WebService1Soap.getUserbyId(Frontend.ServiceReference1.getUserbyIdRequest request) {
            return base.Channel.getUserbyId(request);
        }
        
        public string getUserbyId(int id) {
            Frontend.ServiceReference1.getUserbyIdRequest inValue = new Frontend.ServiceReference1.getUserbyIdRequest();
            inValue.Body = new Frontend.ServiceReference1.getUserbyIdRequestBody();
            inValue.Body.id = id;
            Frontend.ServiceReference1.getUserbyIdResponse retVal = ((Frontend.ServiceReference1.WebService1Soap)(this)).getUserbyId(inValue);
            return retVal.Body.getUserbyIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getUserbyIdResponse> Frontend.ServiceReference1.WebService1Soap.getUserbyIdAsync(Frontend.ServiceReference1.getUserbyIdRequest request) {
            return base.Channel.getUserbyIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Frontend.ServiceReference1.getUserbyIdResponse> getUserbyIdAsync(int id) {
            Frontend.ServiceReference1.getUserbyIdRequest inValue = new Frontend.ServiceReference1.getUserbyIdRequest();
            inValue.Body = new Frontend.ServiceReference1.getUserbyIdRequestBody();
            inValue.Body.id = id;
            return ((Frontend.ServiceReference1.WebService1Soap)(this)).getUserbyIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Frontend.ServiceReference1.getHostedChallengesResponse Frontend.ServiceReference1.WebService1Soap.getHostedChallenges(Frontend.ServiceReference1.getHostedChallengesRequest request) {
            return base.Channel.getHostedChallenges(request);
        }
        
        public string getHostedChallenges(int userId) {
            Frontend.ServiceReference1.getHostedChallengesRequest inValue = new Frontend.ServiceReference1.getHostedChallengesRequest();
            inValue.Body = new Frontend.ServiceReference1.getHostedChallengesRequestBody();
            inValue.Body.userId = userId;
            Frontend.ServiceReference1.getHostedChallengesResponse retVal = ((Frontend.ServiceReference1.WebService1Soap)(this)).getHostedChallenges(inValue);
            return retVal.Body.getHostedChallengesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getHostedChallengesResponse> Frontend.ServiceReference1.WebService1Soap.getHostedChallengesAsync(Frontend.ServiceReference1.getHostedChallengesRequest request) {
            return base.Channel.getHostedChallengesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Frontend.ServiceReference1.getHostedChallengesResponse> getHostedChallengesAsync(int userId) {
            Frontend.ServiceReference1.getHostedChallengesRequest inValue = new Frontend.ServiceReference1.getHostedChallengesRequest();
            inValue.Body = new Frontend.ServiceReference1.getHostedChallengesRequestBody();
            inValue.Body.userId = userId;
            return ((Frontend.ServiceReference1.WebService1Soap)(this)).getHostedChallengesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Frontend.ServiceReference1.getActiveChallengesResponse Frontend.ServiceReference1.WebService1Soap.getActiveChallenges(Frontend.ServiceReference1.getActiveChallengesRequest request) {
            return base.Channel.getActiveChallenges(request);
        }
        
        public string getActiveChallenges(int userId) {
            Frontend.ServiceReference1.getActiveChallengesRequest inValue = new Frontend.ServiceReference1.getActiveChallengesRequest();
            inValue.Body = new Frontend.ServiceReference1.getActiveChallengesRequestBody();
            inValue.Body.userId = userId;
            Frontend.ServiceReference1.getActiveChallengesResponse retVal = ((Frontend.ServiceReference1.WebService1Soap)(this)).getActiveChallenges(inValue);
            return retVal.Body.getActiveChallengesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Frontend.ServiceReference1.getActiveChallengesResponse> Frontend.ServiceReference1.WebService1Soap.getActiveChallengesAsync(Frontend.ServiceReference1.getActiveChallengesRequest request) {
            return base.Channel.getActiveChallengesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Frontend.ServiceReference1.getActiveChallengesResponse> getActiveChallengesAsync(int userId) {
            Frontend.ServiceReference1.getActiveChallengesRequest inValue = new Frontend.ServiceReference1.getActiveChallengesRequest();
            inValue.Body = new Frontend.ServiceReference1.getActiveChallengesRequestBody();
            inValue.Body.userId = userId;
            return ((Frontend.ServiceReference1.WebService1Soap)(this)).getActiveChallengesAsync(inValue);
        }
        
        public int getMaxChallengeId() {
            return base.Channel.getMaxChallengeId();
        }
        
        public System.Threading.Tasks.Task<int> getMaxChallengeIdAsync() {
            return base.Channel.getMaxChallengeIdAsync();
        }
    }
}
